// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4ITSrntTlbkR23LdZ_qtLIsD-K0IBIL4',
    appId: '1:201014046550:web:47953e0e88ad919fafb0f7',
    messagingSenderId: '201014046550',
    projectId: 'testapp-5ffca',
    authDomain: 'testapp-5ffca.firebaseapp.com',
    storageBucket: 'testapp-5ffca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOxI3bBwTgh3Di-Ru_rvRTNgKYk0X2smU',
    appId: '1:201014046550:android:2d1b0c6ee3c9636bafb0f7',
    messagingSenderId: '201014046550',
    projectId: 'testapp-5ffca',
    storageBucket: 'testapp-5ffca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB6vP4OANPM6-Vr7_BOUWBalUt8muib8E',
    appId: '1:201014046550:ios:edc204768e12153dafb0f7',
    messagingSenderId: '201014046550',
    projectId: 'testapp-5ffca',
    storageBucket: 'testapp-5ffca.firebasestorage.app',
    iosBundleId: 'com.example.testFirebase',
  );
}
